"""Copy the Lua mod into TPF2 mods/ and write user_options.lua."""
from __future__ import annotations

import json
import re
from pathlib import Path

from . import atomic

DEFAULT_OPTIONS = {
    "build_streets": True,
    "build_tracks": True,
    "build_subwaytracks": True,
    "build_tramtracks": False,
    "build_bridges": True,
    "build_tunnels": False,
    "build_signals": True,
    "build_autobahn": True,
    "build_streets_street_types": True,
    "build_streets_footway_types": False,
    "build_streets_water": True,
    "build_streets_airport": True,
    "build_buildings_residential": True,
    "build_buildings_commercial": True,
    "build_buildings_industrial": True,
    "skip_nodes_outofbounds": True,
    "crash_type_not_found": False,
    "log_level": 1,
}

# osmdata.lua is handled separately (mtime / completeness). Other Lua always updates.
PRESERVE_IF_EXISTS = {
    "osmdata.lua",
}


_LUA_OPT = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?),\s*$")


def merge_options(*parts: dict | None) -> dict:
    merged = dict(DEFAULT_OPTIONS)
    for part in parts:
        if part:
            merged.update(part)
    return merged


def _read_lua_options(path: Path) -> dict:
    out: dict = {}
    if not path.is_file():
        return out
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return out
    for line in text.splitlines():
        m = _LUA_OPT.match(line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2).strip()
        if raw == "true":
            out[key] = True
        elif raw == "false":
            out[key] = False
        else:
            try:
                out[key] = int(raw) if "." not in raw else float(raw)
            except ValueError:
                out[key] = raw.strip('"')
    return out


def _lua_bool(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return '"' + str(v).replace('"', '\\"') + '"'


def write_options(dest: Path, options: dict) -> None:
    dest = Path(dest)
    extra = {k: v for k, v in _read_lua_options(dest).items() if k not in DEFAULT_OPTIONS}
    merged = merge_options(extra, options)
    lines = ["-- generated by OSM-TPF2 Studio", "return {"]
    for k, v in merged.items():
        lines.append(f"\t{k} = {_lua_bool(v)},")
    lines.append("}")
    atomic.write_text(dest, "\n".join(lines) + "\n")


def _copy_tree(src: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for path in src.rglob("*"):
        rel = path.relative_to(src)
        target = dest / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        if target.name == "osmdata.lua" or target.name.startswith("osmdata_"):
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        atomic.copy_file(path, target)


def _looks_like_loader(path: Path) -> bool:
    try:
        head = path.read_bytes()[:1200]
    except OSError:
        return False
    return b"osmdata_" in head and b"require" in head


def osmdata_bundle(src_lua: Path) -> list[Path]:
    src_lua = Path(src_lua)
    files = [src_lua]
    if src_lua.parent.is_dir():
        files.extend(sorted(src_lua.parent.glob("osmdata_*.lua")))
    seen = set()
    out = []
    for f in files:
        key = f.resolve()
        if key in seen or not f.is_file():
            continue
        seen.add(key)
        out.append(f)
    return out


def should_replace_osmdata(src: Path, dest: Path) -> tuple[bool, str]:
    src = Path(src)
    dest = Path(dest)
    if not src.is_file():
        return False, "no Studio osmdata.lua"
    if dest.exists() and src.resolve() == dest.resolve():
        return False, "source and live path are the same"
    if not dest.exists():
        return True, "live osmdata.lua missing"
    src_m = src.stat().st_mtime
    dest_m = dest.stat().st_mtime
    src_sz = src.stat().st_size
    dest_sz = dest.stat().st_size
    if dest_m > src_m + 1.0:
        return False, "live osmdata.lua is newer than the Studio work file"
    if src_sz < 2048 and dest_sz > 1_000_000 and not _looks_like_loader(src):
        return False, "Studio work file looks incomplete; kept live osmdata.lua"
    if src_m > dest_m + 1.0:
        return True, "Studio work file is newer"
    if src_sz != dest_sz:
        return True, "Studio work file changed"
    return False, "live osmdata.lua kept"


def should_copy_sidecar(src: Path, dest: Path) -> tuple[bool, str]:
    src = Path(src)
    dest = Path(dest)
    if not src.is_file():
        return False, "no Studio osmdata_buildings.lua"
    if dest.exists() and src.resolve() == dest.resolve():
        return False, "source and live path are the same"
    if not dest.exists():
        return True, "live osmdata_buildings.lua missing"
    src_m = src.stat().st_mtime
    dest_m = dest.stat().st_mtime
    src_sz = src.stat().st_size
    dest_sz = dest.stat().st_size
    if dest_m > src_m + 1.0 and dest_sz > 64:
        return False, "live osmdata_buildings.lua is newer"
    if src_sz < 64 and dest_sz > 64:
        return False, "Studio buildings sidecar looks empty; kept live file"
    if src_m > dest_m + 1.0 or src_sz != dest_sz:
        return True, "Studio buildings sidecar is newer"
    return False, "live osmdata_buildings.lua kept"


def install_mod(repo_root: Path, game_mods: Path, osmdata: Path | None, options: dict, progress=None) -> dict:
    def note(msg: str, pct=None) -> None:
        if progress:
            progress(msg, pct)

    target = game_mods / "osm_importer_1"
    src_mod = repo_root / "mod.lua"
    src_res = repo_root / "res"
    src_strings = repo_root / "strings.lua"
    if not src_res.is_dir():
        return {"ok": False, "error": f"Missing {src_res}"}

    note("Creating osm_importer_1…", 4)
    target.mkdir(parents=True, exist_ok=True)
    atomic.copy_file(src_mod, target / "mod.lua")
    if src_strings.is_file():
        atomic.copy_file(src_strings, target / "strings.lua")

    note("Copying Lua scripts and assets…", 18)
    _copy_tree(src_res, target / "res")

    scripts = target / "res" / "scripts" / "osm_importer"
    scripts.mkdir(parents=True, exist_ok=True)

    osmdata_copied = False
    osmdata_note = "no Studio osmdata.lua"
    osmdata_source = ""
    copied_names: list[str] = []
    src_lua = Path(osmdata) if osmdata else None
    if src_lua and src_lua.is_file():
        osmdata_source = str(src_lua)
        dest_lua = scripts / "osmdata.lua"
        replace, osmdata_note = should_replace_osmdata(src_lua, dest_lua)
        if replace:
            bundle = osmdata_bundle(src_lua)
            n = max(1, len(bundle))
            for i, src in enumerate(bundle):
                dest = scripts / src.name
                if src.resolve() == dest.resolve():
                    continue
                start = 55 + 35 * i / n
                end = 55 + 35 * (i + 1) / n
                note(f"Copying {src.name}…", start)
                atomic.copy_file(src, dest, progress=progress, start_pct=start, end_pct=end)
                copied_names.append(src.name)
                if src.name == "osmdata.lua":
                    osmdata_copied = True
            osmdata_note = "copied " + ", ".join(copied_names)
        else:
            note(osmdata_note, 90)
            sidecar = src_lua.parent / "osmdata_buildings.lua"
            dest_side = scripts / "osmdata_buildings.lua"
            copy_side, side_note = should_copy_sidecar(sidecar, dest_side)
            if copy_side:
                note("Copying osmdata_buildings.lua sidecar…", 92)
                atomic.copy_file(sidecar, dest_side, progress=progress, start_pct=92, end_pct=94)
                copied_names.append("osmdata_buildings.lua")
                osmdata_note = osmdata_note + "; " + side_note
            else:
                note(side_note, 92)
                osmdata_note = osmdata_note + "; " + side_note

    note("Writing user_options.lua…", 95)
    write_options(scripts / "user_options.lua", options)
    project = {
        "game_mods": str(game_mods),
        "target": str(target),
        "options": merge_options(options),
        "osmdata_source": osmdata_source,
        "osmdata_copied": osmdata_copied,
        "osmdata_note": osmdata_note,
    }
    atomic.write_text(scripts / "studio_project.json", json.dumps(project, indent=2) + "\n")
    note("Installed.", 100)
    return {
        "ok": True,
        "target": str(target),
        "osmdata": (scripts / "osmdata.lua").is_file(),
        "osmdata_copied": osmdata_copied,
        "osmdata_note": osmdata_note,
        "osmdata_source": osmdata_source,
        "osmdata_files": copied_names,
        "preserved": sorted(PRESERVE_IF_EXISTS),
    }
