import os
import sys
from datetime import datetime
from pathlib import Path

import luadata

import read_osm
import convert_data
import optimize_edges
import sort_edges
from lua_remove_nil import drop_removed_nodes, lua_remove_nil

_OSMDATA_CHUNKS = ("towns", "nodes", "edges", "areas", "objects", "paths", "buildings")

_LOADER = '''-- generated by OSM-TPF2 converter; chunks load on first access
local names = {
	towns = true, nodes = true, edges = true, areas = true, objects = true, paths = true, buildings = true,
}
local chunks = {}
local function loadchunk(name)
	if chunks[name] ~= nil then
		return chunks[name]
	end
	local ok, data = pcall(require, "osm_importer.osmdata_" .. name)
	if not ok then
		print("osmdata: missing chunk " .. name .. " " .. tostring(data))
		data = {}
	end
	chunks[name] = data
	return data
end
return setmetatable({}, {
	__index = function(_, k)
		if names[k] then
			return loadchunk(k)
		end
	end,
})
'''


def _atomic_luadata_write(path, payload):
    path = os.path.abspath(path)
    tmp = path + ".part"
    luadata.write(tmp, payload, indent="\t")
    os.replace(tmp, path)


def _atomic_text_write(path, text):
    path = os.path.abspath(path)
    tmp = path + ".part"
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, path)


def write_osmdata_lua(outfile, data):
    """Write split chunks plus a small lazy loader as osmdata.lua."""
    out = Path(outfile)
    out.parent.mkdir(parents=True, exist_ok=True)
    empty = {"towns": {}, "nodes": {}, "edges": {}, "areas": {}, "objects": [], "paths": {}, "buildings": []}
    for name in _OSMDATA_CHUNKS:
        payload = data.get(name, empty.get(name))
        chunk = out.parent / f"osmdata_{name}.lua"
        print(f"Write Lua chunk {name}")
        _atomic_luadata_write(str(chunk), payload)
    _atomic_text_write(str(out), _LOADER)
    return str(out)


def convert_osm(infile, outfile, bounds_length, bounds, log_file=None):
    """Convert OSM XML to osmdata.lua. bounds_length is (x_m, y_m)."""
    old_out, old_err = sys.stdout, sys.stderr
    log_handle = None
    if log_file:
        os.makedirs(os.path.dirname(os.path.abspath(log_file)) or ".", exist_ok=True)
        log_handle = open(log_file, "w", encoding="utf-8", buffering=1)
        sys.stdout = log_handle
        sys.stderr = log_handle
    try:
        print("#" * 16 + "  OSM-TPF2 CONVERTER  " + "#" * 16)
        print("Startup:", datetime.now())
        start = datetime.now()
        if not bounds:
            bounds = read_osm.read_bounds(infile)
            print("Using <bounds> from OSM file")
        print("Map Bounds defined:", bounds)
        print("Map size (m):", bounds_length)

        print("=" * 16 + " Parse OSM XML data " + "=" * 16)
        nodes, ways, relations = read_osm.read(infile, bounds)

        print("=" * 16 + " Convert/Transform data " + "=" * 16)
        data = convert_data.convert(nodes, ways, relations, bounds, bounds_length)

        print("=" * 16 + " Optimize Edges/geometry " + "=" * 16)
        optimize_edges.optimize(data)

        print("=" * 16 + " Sort Edges " + "=" * 16)
        data["edges"] = sort_edges.sort(data["edges"])

        data = lua_remove_nil(data)
        data = drop_removed_nodes(data)

        print("=" * 16 + " Write Lua file " + "=" * 16)
        write_osmdata_lua(outfile, data)
        print(f"Successfully converted OSM data to: '{outfile}'")
        print("\n  ".join([
            "Data contains:",
            f"Towns: {len(data['towns'])}",
            f"Nodes: {len(data['nodes'])}",
            f"Edges: {len(data['edges'])}",
            f"Areas: {sum(len(area) for area in data['areas'].values())}",
            f"Objects: {len(data['objects'])}",
            f"Buildings: {len(data.get('buildings') or [])}",
        ]))
        print(f"Execution time: {datetime.now() - start} s")
        return {
            "ok": True,
            "towns": len(data["towns"]),
            "nodes": len(data["nodes"]),
            "edges": len(data["edges"]),
            "areas": sum(len(area) for area in data["areas"].values()),
            "objects": len(data["objects"]),
            "buildings": len(data.get("buildings") or []),
            "out": outfile,
        }
    finally:
        sys.stdout = old_out
        sys.stderr = old_err
        if log_handle:
            log_handle.close()


def convert_buildings_only(infile, outfile, bounds_length, bounds, log_file=None):
    """Write osmdata_buildings.lua without replacing towns/nodes/edges."""
    old_out, old_err = sys.stdout, sys.stderr
    log_handle = None
    if log_file:
        os.makedirs(os.path.dirname(os.path.abspath(log_file)) or ".", exist_ok=True)
        log_handle = open(log_file, "w", encoding="utf-8", buffering=1)
        sys.stdout = log_handle
        sys.stderr = log_handle
    try:
        print("#" * 16 + "  OSM-TPF2 BUILDINGS  " + "#" * 16)
        print("Startup:", datetime.now())
        start = datetime.now()
        if not bounds:
            bounds = read_osm.read_bounds(infile)
            print("Using <bounds> from OSM file")
        print("Map Bounds defined:", bounds)
        print("Map size (m):", bounds_length)

        print("=" * 16 + " Parse building ways " + "=" * 16)
        nodes, ways = read_osm.read_building_ways(infile, bounds)

        print("=" * 16 + " Convert footprints " + "=" * 16)
        buildings = convert_data.extract_buildings(nodes, ways, bounds, bounds_length)

        print("=" * 16 + " Write Lua file " + "=" * 16)
        out = os.path.abspath(outfile)
        os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
        _atomic_luadata_write(out, buildings)
        print(f"Successfully wrote buildings sidecar: '{out}'")
        print(f"Buildings: {len(buildings)}")
        print(f"Execution time: {datetime.now() - start} s")
        return {
            "ok": True,
            "buildings": len(buildings),
            "out": out,
        }
    finally:
        sys.stdout = old_out
        sys.stderr = old_err
        if log_handle:
            log_handle.close()


def _cli():
    args = sys.argv[1:]
    buildings = False
    log_file = None
    positional = []
    i = 0
    while i < len(args):
        if args[i] == "--buildings":
            buildings = True
        elif args[i] == "--log" and i + 1 < len(args):
            i += 1
            log_file = args[i]
        else:
            positional.append(args[i])
        i += 1

    infile = positional[0] if len(positional) > 0 else "map.osm"
    outfile = positional[1] if len(positional) > 1 else ("osmdata_buildings.lua" if buildings else "osmdata.lua")
    bounds_length = (16384, 16384)
    if len(positional) > 2:
        bounds_length = tuple(map(int, positional[2].split(",")))
        assert len(bounds_length) == 2
    bounds = None
    if len(positional) > 3:
        coords = map(float, positional[3].split(","))
        bounds = dict((key, c) for key, c in zip(["minlat", "minlon", "maxlat", "maxlon"], coords))

    if log_file:
        fn = convert_buildings_only if buildings else convert_osm
        stats = fn(infile, outfile, bounds_length, bounds, log_file=log_file)
        if not stats or not stats.get("ok"):
            sys.exit(1)
        return

    sys.stdout = open("log.txt", "w", encoding="utf-8")
    sys.stderr = sys.stdout
    if buildings:
        convert_buildings_only(infile, outfile, bounds_length, bounds, log_file=None)
    else:
        convert_osm(infile, outfile, bounds_length, bounds, log_file=None)


if __name__ == "__main__":
    _cli()
